# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 741, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timer_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timer_label.setFont(font)
        self.timer_label.setObjectName("timer_label")
        self.horizontalLayout.addWidget(self.timer_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.title_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lvl_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lvl_label.setFont(font)
        self.lvl_label.setObjectName("lvl_label")
        self.horizontalLayout.addWidget(self.lvl_label)
        self.timer_label_2 = QtWidgets.QLabel(Form)
        self.timer_label_2.setGeometry(QtCore.QRect(30, 60, 110, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timer_label_2.setFont(font)
        self.timer_label_2.setText("")
        self.timer_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label_2.setObjectName("timer_label_2")
        self.seq_label = QtWidgets.QLabel(Form)
        self.seq_label.setGeometry(QtCore.QRect(232, 250, 337, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.seq_label.setFont(font)
        self.seq_label.setText("")
        self.seq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.seq_label.setObjectName("seq_label")
        self.info_label = QtWidgets.QLabel(Form)
        self.info_label.setGeometry(QtCore.QRect(232, 211, 337, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.info_label.setFont(font)
        self.info_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.user_input_field = QtWidgets.QLineEdit(Form)
        self.user_input_field.setGeometry(QtCore.QRect(232, 295, 337, 30))
        self.user_input_field.setMinimumSize(QtCore.QSize(0, 30))
        self.user_input_field.setObjectName("user_input_field")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(319, 360, 162, 41))
        self.start_button.setObjectName("start_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timer_label.setText(_translate("Form", "         "))
        self.title_label.setText(_translate("Form", "Режим испытания"))
        self.lvl_label.setText(_translate("Form", "Уровень"))
        self.info_label.setText(_translate("Form", "Запомните последовательность"))
        self.start_button.setText(_translate("Form", "Начать"))
