# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)

        self.widget = Form
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.info_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.info_label.setFont(font)
        self.info_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.gridLayout.addWidget(self.info_label, 3, 2, 1, 1)
        self.seq_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.seq_label.setFont(font)
        self.seq_label.setText("")
        self.seq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.seq_label.setObjectName("seq_label")
        self.gridLayout.addWidget(self.seq_label, 4, 2, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 7, 2, 1, 1)
        self.return_btn = QtWidgets.QPushButton(self.widget)
        self.return_btn.setObjectName("return_btn")
        self.gridLayout.addWidget(self.return_btn, 9, 4, 1, 1)
        self.user_input_field = QtWidgets.QLineEdit(self.widget)
        self.user_input_field.setMinimumSize(QtCore.QSize(0, 30))
        self.user_input_field.setObjectName("user_input_field")
        self.gridLayout.addWidget(self.user_input_field, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.timer_label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timer_label_2.setFont(font)
        self.timer_label_2.setText("")
        self.timer_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label_2.setObjectName("timer_label_2")
        self.gridLayout.addWidget(self.timer_label_2, 0, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 2, 2, 1)
        self.timer_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timer_label.setFont(font)
        self.timer_label.setText("")
        self.timer_label.setObjectName("timer_label")
        self.gridLayout.addWidget(self.timer_label, 1, 0, 1, 1)
        self.lvl_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lvl_label.setFont(font)
        self.lvl_label.setObjectName("lvl_label")
        self.gridLayout.addWidget(self.lvl_label, 0, 4, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 8, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.info_label.setText(_translate("Form", "Запомните последовательность"))
        self.start_button.setText(_translate("Form", "Начать"))
        self.return_btn.setText(_translate("Form", "Вернуться в меню"))
        self.title_label.setText(_translate("Form", "Режим испытания"))
        self.lvl_label.setText(_translate("Form", "Уровень"))
        self.timer_label.setText(_translate("Form", "         "))
